// One-off audit: cross-reference the MODELS catalog against the keyway (veh) records
// to find model/year combos that resolve to NO key info (the "nothing shows up" gaps).
const fs = require('fs');
const code = fs.readFileSync(__dirname + '/bittings-app/app/lishi-seed.js', 'utf8');
const window = {};
const noop = () => {};
const localStorage = { getItem: () => null, setItem: noop, removeItem: noop };
const document = { addEventListener: noop, getElementById: () => null, querySelector: () => null,
  querySelectorAll: () => [], createElement: () => ({ style:{}, appendChild: noop, setAttribute: noop }),
  head: { appendChild: noop }, body: { appendChild: noop }, documentElement: {} };
const navigator = { userAgent: '' };
try {
  new Function('window','localStorage','document','navigator','setTimeout', code)(window, localStorage, document, navigator, noop);
} catch (e) { console.error('load error:', e.message); }

const seed = window.TKS_LISHI_SEED || {};
const MODELS = seed.models || {};
const VEH = seed.veh || [];
console.log('Loaded: makes=' + Object.keys(MODELS).length + ', keyway records=' + VEH.length + '\n');

function vehMatch(make, model, year) {
  const mk = (make||'').toLowerCase(), md = (model||'').toLowerCase();
  return VEH.some(r => {
    if ((r.make||'').toLowerCase() !== mk) return false;
    const ys = parseInt(r.year_start,10), ye = parseInt(r.year_end,10);
    if (!(year >= ys && year <= ye)) return false;
    const rm = (r.model||'').toLowerCase();
    return rm === md || rm.indexOf(md) >= 0 || md.indexOf(rm) >= 0;
  });
}

const gaps = [];
Object.keys(MODELS).sort().forEach(make => {
  (MODELS[make]||[]).forEach(row => {
    const model = row[0], ys = parseInt(row[1],10), ye = parseInt(row[2],10) || (new Date().getFullYear());
    // sample the start, middle, end years of the model's run
    const yearsToCheck = [...new Set([ys, Math.round((ys+ye)/2), ye])];
    const missing = yearsToCheck.filter(y => !vehMatch(make, model, y));
    if (missing.length === yearsToCheck.length) {
      gaps.push({ make, model, range: ys + '-' + ye });   // no keyway record anywhere in its run
    } else if (missing.length) {
      gaps.push({ make, model, range: ys + '-' + ye, partial: 'missing years: ' + missing.join(', ') });
    }
  });
});

const full = gaps.filter(g => !g.partial);
const partial = gaps.filter(g => g.partial);
const total = Object.values(MODELS).reduce((a,m)=>a+m.length,0);

let md = '# Vehicle key-data gaps — for owner review\n\n';
md += '_Auto-generated by `_vehicle_audit.js`: cross-references the make/model dropdown catalog against the keyway (Lishi) records in `app/lishi-seed.js`. Fill from your **Ilco 2025** / AKS / Strattec references — do not guess._\n\n';
md += '- Model lines in the catalog: **' + total + '**\n';
md += '- Keyway records on file: **' + VEH.length + '**\n';
md += '- **No keyway record at all (priority):** **' + full.length + '**\n';
md += '- Partial (only start/end years of the run uncovered): **' + partial.length + '**\n\n';

function section(title, list) {
  let s = '## ' + title + '\n\n';
  let cur = '';
  list.forEach(g => {
    if (g.make !== cur) { cur = g.make; s += '\n**' + cur + '**\n'; }
    s += '- ' + g.model + ' (' + g.range + ')' + (g.partial ? ' — ' + g.partial : '') + '\n';
  });
  return s + '\n';
}
md += section('A) No key info at all — these show "nothing" on lookup', full);
md += section('B) Partial — covered except the listed years', partial);

fs.writeFileSync(__dirname + '/VEHICLE_DATA_GAPS.md', md);
console.log('Wrote VEHICLE_DATA_GAPS.md');
console.log('Catalog lines: ' + total + ' | No record: ' + full.length + ' | Partial: ' + partial.length);
// quick spot-checks the owner named
['Lincoln','Chevrolet'].forEach(mk => {
  const g = full.concat(partial).filter(x => x.make === mk);
  console.log('\n' + mk + ' gaps: ' + g.map(x => x.model+' ('+x.range+')'+(x.partial?' ['+x.partial+']':'')).join(' | '));
});
